FROM archlinux:base-devel-20260712.0.555161@sha256:212b1e518e94ee9c52be55e8a32da75fcf11e7b5610b80b49479e67880102406

RUN printf 'Server = https://archive.archlinux.org/repos/2026/07/12/$repo/os/$arch\n' \
      >/etc/pacman.d/mirrorlist \
    && pacman -Sy --noconfirm --needed git python python-pip curl sudo \
    && python -m venv /tmp/doubt-acceptance-tools

WORKDIR /workspace
COPY . /workspace

RUN /tmp/doubt-acceptance-tools/bin/pip install --disable-pip-version-check \
      --require-hashes -r requirements/build.txt

ENV PATH=/tmp/doubt-acceptance-tools/bin:/usr/local/sbin:/usr/local/bin:/usr/bin
ENV PYTHONDONTWRITEBYTECODE=1
ENV XDG_CACHE_HOME=/tmp/doubt-acceptance-cache

CMD ["./acceptance/container/check"]
